apiVersion: apps/v1
kind: Deployment
metadata:
  name: maison-aura-frontend
  namespace: maison-aura
spec:
  selector:
    matchLabels:
      app: maison-aura-frontend
  template:
    metadata:
      labels:
        app: maison-aura-frontend
    spec:
      containers:
        - name: frontend
          image: __ACR_LOGIN_SERVER__/maison-aura-frontend:__BUILD_ID__
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 8Mi
            limits:
              cpu: 100m
              memory: 32Mi
